#!/usr/bin/env bash
#
# Checks every host port the stack wants to publish, and suggests free
# replacements for any that are taken.
#
#   ./scripts/preflight.sh          # report only
#   ./scripts/preflight.sh --write  # write a .env that avoids the conflicts
#
# Run this before `docker compose up` to find every collision at once, instead
# of discovering them one container at a time.

set -uo pipefail

WRITE=0
TOOLS=0
for arg in "$@"; do
  case "$arg" in
    --write) WRITE=1 ;;
    --tools) TOOLS=1 ;;
  esac
done

if [[ -t 1 ]]; then
  G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; B=$'\033[1m'; N=$'\033[0m'
else
  G=""; R=""; Y=""; B=""; N=""
fi

# var:default:description
# The base stack publishes only these four. Everything else stays inside the
# compose network, which is why it cannot collide with anything on your host.
PORTS=(
  "OW_API_PORT:8080:Fraud API"
  "OW_UI_PORT:5173:Dashboard UI"
  "OW_PROMETHEUS_PORT:9090:Prometheus"
  "OW_GRAFANA_PORT:3000:Grafana"
)

# Published only by docker-compose.tools.yml. Checked when --tools is passed.
TOOLS_PORTS=(
  "OW_PG_PORT:5432:PostgreSQL"
  "OW_KAFKA_PORT:19092:Redpanda Kafka API"
  "OW_SIMULATOR_PORT:8081:Transaction simulator"
  "OW_ENGINE_PORT:8082:Fraud engine"
)

# Portable listener check: bash's /dev/tcp works on macOS and Linux without lsof.
in_use() {
  (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1 && { exec 3<&- 3>&-; return 0; }
  return 1
}

# What is holding it, if we can tell. Best-effort; lsof is not always present.
holder() {
  command -v lsof >/dev/null 2>&1 || return 0
  lsof -nP -iTCP:"$1" -sTCP:LISTEN 2>/dev/null | awk 'NR==2 {print $1}'
}

next_free() { # next_free <start> — first free port at or above start
  local p="$1"
  while in_use "$p"; do p=$((p + 1)); done
  printf '%s' "$p"
}

printf '%sOverwatch preflight — host port check%s\n\n' "$B" "$N"

conflicts=0
declare -a OVERRIDES=()

[[ "$TOOLS" -eq 1 ]] && PORTS+=("${TOOLS_PORTS[@]}")

for entry in "${PORTS[@]}"; do
  IFS=':' read -r var def desc <<< "$entry"
  want="${!var:-$def}"

  if in_use "$want"; then
    who=$(holder "$want")
    free=$(next_free $((want + 1)))
    printf '  %sBUSY%s  %-22s %-6s' "$R" "$N" "$desc" "$want"
    [[ -n "$who" ]] && printf ' (held by %s)' "$who"
    printf ' -> suggest %s%s%s\n' "$Y" "$free" "$N"
    OVERRIDES+=("$var=$free")
    conflicts=$((conflicts + 1))
  else
    printf '  %sFREE%s  %-22s %s\n' "$G" "$N" "$desc" "$want"
  fi
done

printf '\n'

if [[ "$conflicts" -eq 0 ]]; then
  printf '%sAll ports free — docker compose up should bind cleanly.%s\n' "$G" "$N"
  exit 0
fi

printf '%s%d conflict(s).%s Add these to .env:\n\n' "$R" "$conflicts" "$N"
printf '    %s\n' "${OVERRIDES[@]}"
printf '\n'

if [[ "$WRITE" -eq 1 ]]; then
  [[ -f .env ]] && cp .env ".env.backup.$(date +%s)" && printf 'Existing .env backed up.\n'
  {
    printf '# Generated by scripts/preflight.sh on %s\n' "$(date)"
    printf '# Host-side ports only; container ports are unchanged.\n\n'
    printf '%s\n' "${OVERRIDES[@]}"
  } >> .env
  printf '%sWritten to .env — run: docker compose up%s\n' "$G" "$N"
else
  printf 'Re-run with %s--write%s to apply them automatically.\n' "$B" "$N"
fi
exit 1
